name: Build & Tests
run-name: 'Build & Tests: ${{ github.head_ref || github.ref_name }}'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: celostats-server-${{ github.ref }}
  cancel-in-progress: false

env:
  NODE_VERSION: 20

defaults:
  run:
    shell: bash --login -eo pipefail {0}

jobs:
  build:
    name: Build celostats-server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        # Disable until we can figure out how to configure to load properly with new versions
        if: false
        run: yarn test
